version: "3.9"
services:

  mongo:
    image: mongo:4.4.6
    restart: always
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
    #    environment:
    #      MONGO_INITDB_DATABASE : "handover"
    #      MONGO_INITDB_ROOT_USERNAME : "username"
    #      MONGO_INITDB_ROOT_PASSWORD : "password"
    networks:
      - network

  resumaxapi:
    image: node:17.8.0
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    env_file:
      - ./vars.env
    working_dir: /app
    networks:
      - network
    command: bash -c "npm install && npm run build && npm start"

networks:
  network:
    name : resumax
#    external: true
